### ISSUE TITLE
Saving credentials to external storage failed

### ISSUE THREAD

**Issue by mohammedbabelly** [pushy-me/pushy-demo-flutter#1]
I cloned the pushy-demo-flutter and run it on my Android device, it registers the device token but it did not save it to external storage!

so every time I reinstall the app it registers a new device at the dashboard!

can I find another way to save the device token, or delete the unused tokens in the dashboard so you do not charge me for unused tokens every year?

or can I at least save the device token for every user in my database and every time the app reinstalled I register the device with the old token that saved in my database????

**Comment by mohammedbabelly** [comment]
✓ Built build/app/outputs/apk/debug/app-debug.apk.
D/Pushy   (10506): **External storage access failed**
D/ViewRootImpl@f5c0106[MainActivity](10506): MSG_WINDOW_FOCUS_CHANGED 0
D/Pushy   (10506): External storage access failed
D/NetworkSecurityConfig(10506): No Network Security Config specified, using platform default
I/System.out(10506): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(10506): (HTTPLog)-Static: isSBSettingEnabled false
D/InputTransport(10506): Input channel destroyed: fd=92
D/Pushy   (10506): **Saving credentials to external storage failed**
D/Pushy   (10506): Creating service
D/Pushy   (10506): Connecting...
I/System.out(10506): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(10506): (HTTPLog)-Static: isSBSettingEnabled false
D/Pushy   (10506): Internet connected
D/Pushy   (10506): Already reconnecting
I/flutter (10506): Device token: 522db7f2901562238653fe
W/Pushy   (10506): Flutter app is listening for notifications
D/Pushy   (10506): Broker: tcp://54.174.144.201:1883
D/Pushy   (10506): Device Token: 522db7f2901562238653fe
D/Pushy   (10506): Device Auth Key: 770aa25f4f7384db4349f1... [truncated]
D/Pushy   (10506): Wi-Fi lock acquired
D/Pushy   (10506): Connected successfully (sending keep alive every 300 seconds)
D/ViewRootImpl@f5c0106[MainActivity](10506): MSG_WINDOW_FOCUS_CHANGED 1
D/ViewRootImpl@f5c0106[MainActivity](10506): mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true -782940160}
V/InputMethodManager(10506): Starting input: tba=android.view.inputmethod.EditorInfo@906881 nm : me.pushy.example ic=null
I/InputMethodManager(10506): [IMM] startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(10506): Input channel constructed: fd=110
D/ViewRootImpl@f5c0106[MainActivity](10506): MSG_WINDOW_FOCUS_CHANGED 0
D/ViewRootImpl@f5c0106[MainActivity](10506): MSG_WINDOW_FOCUS_CHANGED 1
D/ViewRootImpl@f5c0106[MainActivity](10506): mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true -782940160}
D/ViewRootImpl@f5c0106[MainActivity](10506): Relayout returned: oldFrame=[0,0][720,1280] newFrame=[0,0][720,1280] result=0x1 surface={isValid=true -782940160} surfaceGenerationChanged=false
D/ViewRootImpl@f5c0106[MainActivity](10506): MSG_WINDOW_FOCUS_CHANGED 0
D/SurfaceView(10506): Relayout returned: oldFrame=[0,0][720,1280] newFrame=[0,0][720,1280] result=0x5 surface={Surface(name=null)/@0xb021df4 isValid=false 0}
D/ViewRootImpl@f5c0106[MainActivity](10506): mHardwareRenderer.destroy()#1
D/ViewRootImpl@f5c0106[MainActivity](10506): Relayout returned: oldFrame=[0,0][720,1280] newFrame=[0,0][720,1280] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=true
D/InputTransport(10506): Input channel destroyed: fd=110
D/ViewRootImpl@f5c0106[MainActivity](10506): mHardwareRenderer.destroy()#1
D/ViewRootImpl@f5c0106[MainActivity](10506): Relayout returned: oldFrame=[0,0][720,1280] newFrame=[0,0][720,1280] result=0x1 surface={isValid=false 0} surfaceGenerationChanged=false
D/ViewRootImpl@f5c0106[MainActivity](10506): mHardwareRenderer.destroy()#1
D/ViewRootImpl@f5c0106[MainActivity](10506): Relayout returned: oldFrame=[0,0][720,1280] newFrame=[0,0][720,1280] result=0x1 surface={isValid=false 0} surfaceGenerationChanged=false
D/SurfaceView(10506): Relayout returned: oldFrame=[0,0][720,1280] newFrame=[0,0][720,1280] result=0x7 surface={Surface(name=null)/@0xb021df4 isValid=true -782940160}
D/mali_winsys(10506): EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [720x1280]-format:1
D/ViewRootImpl@f5c0106[MainActivity](10506): Relayout returned: oldFrame=[0,0][720,1280] newFrame=[0,0][720,1280] result=0x7 surface={isValid=true -765558784} surfaceGenerationChanged=true
D/ViewRootImpl@f5c0106[MainActivity](10506): mHardwareRenderer.initialize() mSurface={isValid=true -765558784} hwInitialized=true
D/mali_winsys(10506): EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [720x1280]-format:1
D/ViewRootImpl@f5c0106[MainActivity](10506): MSG_WINDOW_FOCUS_CHANGED 1
D/ViewRootImpl@f5c0106[MainActivity](10506): mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true -765558784}
V/InputMethodManager(10506): Starting input: tba=android.view.inputmethod.EditorInfo@219fd26 nm : me.pushy.example ic=null
I/InputMethodManager(10506): [IMM] startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(10506): Input channel constructed: fd=90
D/Pushy   (10506): Sending keep alive

**Comment by pushy** [comment]
Hi @mohammedbabelly,
Thanks for your inquiry. I'd be glad to assist.

Indeed, you can store the Pushy device credentials in your backend for persistence between app reinstalls.

1) Please update the [Pushy Flutter SDK](https://pushy.me/docs/additional-platforms/flutter) in your app by editing the `pubspec.yaml` in the root directory of your project and updating the `pushy_flutter` package version to `1.0.11`:
```
pushy_flutter: 1.0.11
```

Then, run `flutter pub get` to fetch the new package.

2) Modify your implementation to check whether your backend has the device's Pushy credentials before calling `Pushy.register()` on the device. 

3) If not, call `Pushy.register()` and retrieve the device credentials (token + auth key combination) using the following code (Android only):

```
// Only for Android (wrap this code in try-catch as it may throw an exception)
if (Platform.isAndroid) {
   // Register the device for push notifications
   String deviceToken = await Pushy.register();

   // Fetch device credentials
   Map credentials = await Pushy.getDeviceCredentials();

   // Store these values in your backend:
   // credentials["token"]
   // credentials["authKey"]
}
```

4) Store the `credentials["token"]` and `credentials["authKey"]` in your backend server.

5) Before calling `Pushy.register()`, try fetching these values from your backend for the current device/user.

4) If your backend has the credentials stored for the current device, you can assign them as follows:

```
// Only for Android
if (Platform.isAndroid) {
  // From your backend
  String token = '....';
  String authKey = '....';

  // After reinstall, fetch these values from your backend and reassign them:
  await Pushy.setDeviceCredentials({'token': token, 'authKey': authKey]});
}
```
5) Now the device will use the previously assigned device token.

Please let me know if you have any questions.
