### ISSUE TITLE
[Android] Example project not receiving Push Notification when app is terminated

### ISSUE THREAD

**Issue by duy-mai-otsv** [pushy-me/pushy-demo-flutter#3]
Hello Pushy Team,

I have encountered a problem when running the example application. I am not able to receive any push notifications when the app is terminated. However, I am able to receive push notifications normally when the app is in the foreground and background.

Flutter logs

> Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 2.10.4, on macOS 11.6 20G165 darwin-x64, locale
    en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
• No issues found!

**Comment by pushy** [comment]
Hi @duy-mai-otsv,
Thanks for creating this issue. We'd be glad to help you investigate this issue further.

If you could please provide the following information about the device experiencing this issue, that would be great:

1) Device manufacturer
2) Device model name
3) Android OS version

Thanks for your help!

**Comment by duy-mai-otsv** [comment]
Hi @pushy 

Device manufacturer: Google
Device model name: Pixel 6
Android OS version: Android 12

**Comment by duy-mai-otsv** [comment]
@pushy Buzz!!!

**Comment by pushy** [comment]
Hi @duy-mai-otsv,
[Doze mode and App Standby](https://developer.android.com/training/monitoring-device-state/doze-standby.html) may temporarily suspend network and background execution for your app when it goes to background and the phone is idle on Android 9 and up.

To ensure your users will be able to receive notifications in Doze mode, please implement one of the solutions mentioned in this article:
https://support.pushy.me/hc/en-us/articles/360043423332-How-can-I-send-notifications-to-Android-devices-in-Doze-power-saving-mode-

Please let us know if you require any further assistance with this issue.

**Comment by duy-mai-otsv** [comment]
Hi @pushy 
I have tried the above solution, but it seems not to work for me.
I am trying to implement pushy for my Flutter project. And I have tried your example project by Flutter, but the same result.
I found an issue related to foreground #2. In this issue, you have a commented "there is currently no support for foreground notification functionality in the Pushy Flutter SDK".

P/s: My team needs to release applications for China mainland, so we can't use FCM fallback way.

**Comment by pushy** [comment]
Hi @duy-mai-otsv,
It is now possible to use foreground service functionality in Flutter, by following these steps:

1) Add the following permission in your `android/app/src/main/AndroidManifest.xml`, inside the `<manifest>` tag:

```
<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
```

2) Add the following dependency to your `android/app/build.gradle` file:
```
implementation 'me.pushy:sdk:1.0.85'
```

3) Edit `MainActivity.java` located in your `android/app/src/main/java/**/` folder:

**Find:**
```
public class MainActivity extends FlutterActivity {
```

**Add below:**
```
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Pushy foreground service implementation
        Intent notificationIntent = new Intent(this, MainActivity.class);
        PendingIntent pendingIntent = PendingIntent.getActivity(this, 0, notificationIntent, 0);

        // Set title & description for the ongoing notification
        String appName = getPackageManager().getApplicationLabel(getApplicationInfo()).toString();
        String description = "App is running";

        // Android O and newer requires notification channels
        // to be created prior to dispatching a notification
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            NotificationChannel channel = new NotificationChannel("pushy_ongoing", appName, NotificationManager.IMPORTANCE_MIN);
            channel.setDescription(description);

            // Register the channel with the system
            NotificationManager notificationManager = getSystemService(NotificationManager.class);
            notificationManager.createNotificationChannel(channel);
        }

        // Create foreground notification using pushy_ongoing notification channel (customize as necessary)
        Notification notification = new NotificationCompat.Builder(this, "pushy_ongoing")
                .setContentTitle(appName)
                .setContentText(description)
                .setSmallIcon(android.R.drawable.ic_dialog_info)
                .setContentIntent(pendingIntent)
                .build();

        // Configure Pushy SDK to start a foreground service with this notification
        // Must be called before Pushy.listen();
        PushySocketService.setForegroundNotification(notification);
    }
```

Run your app and observe if a foreground notification is displayed, which indicates that the SDK is now running in foreground service mode.
